### ISSUE TITLE
data visualization storage exercise

### ISSUE THREAD

**Issue by emtelgen** [MSU-ICER/cloudcomputingfellowship#23]
I was able to use the scripts and create the images fairly easily. People might run into issues here and there with incorrect file paths or not using the script correctly, but it is doable if you follow the instructions. You say it's not meant to be a step-by-step tutorial so although people might have more issues, there's nothing preventing them from completing the exercise if done correctly.

Things I struggled with:
I didn't really know how to work with the Azure storage account and VM. Everything I did was local in the VM. I tried to output that to a storage account but ran into permissions errors. I'm sure there's a right way to do this and I'll keep researching online but that's the biggest challenge of this exercise for me. I think providing a little more guidance (what type of storage to use: container, file share, etc?) would be beneficial for the exercise.

**Comment by billspat** [comment]
I see that what I didn't ask explicitly was to combine this exercise with the one where you mounted a "file share" storage to a VM.    In Windows, that would give you a new drive letter (Z: is the default).   If you do that first, then you can use that file share to download weather data to it, and then read the data from a script on the VM, then save the output to that.     Given that description, does it make more sense how you'd use storage?  If so, how would you change the wording of the exercise to make it more clear?

**Comment by billspat** [comment]
Next to-do item for this exercise is to fix the R code to work with downloaded data from MeteoStat , see https://github.com/billspat/cloud_computing_script_exercise/issues/3

**Comment by emtelgen** [comment]
I've been able to complete the exercise!
Notes that weren't explicitly stated that people might run into trouble with:
- When signing into their fileshare on the vm, the username and password is not the azure account password. the username is the name of their file share and password is a file share key. This is found on the "Access Keys" tab in the file share and they need to click "Show" on any of the keys they choose to copy
- need to be working in the network location that is set up when they connect their file share to the vm. Not their C drive
- it was easier for me to just move the hourly_weather.csv file to the Python folder so I didn't have to specify the path when running the script to create the png file. Not necessary, but people may find it easier 
- Have to create a snapshot in the file share upon completion! Or else that files will just be attached to the VM and destroyed

**Comment by billspat** [comment]
great insights!   

That last item is something I didn't know about!  Would you add a link to the Azure documentation describing the process and the kind of snapshot you are creating (there are different things called snapshots in Azure, unfortunately).
