### ISSUE TITLE
fix link in readings

### ISSUE THREAD

**Issue by emtelgen** [MSU-ICER/cloudcomputingfellowship#27]
[Tools And Technologies For The Implementation Of Big Data, Richard J. Self, Dave Voorhis] link takes me to sharepoint i can't personally access. i use link under it and have to put my email in to be able to access it: change the wording so people better understand how to access the reading

I also can't find it in the MSU digital library as an actual e-book. Removing the link to library book to not confuse people

**Comment by billspat** [comment]
I believe this was fixed by Emily and merge in https://github.com/MSU-ICER/cloudcomputingfellowship/pull/28
